global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'planning-estiam'
    static_configs:
      - targets: ['planning-estiam:8000']
    metrics_path: '/metrics'

  - job_name: 'planning-estiam-staging'
    static_configs:
      - targets: ['planning-estiam-staging:8000']
    metrics_path: '/metrics'
